window:
  width: 640
  height: 480
  title: TowerDefence2
  max_fps: 60

project:
  name: TowerDefence2
  sources: src
  maps: maps
  logs: logs
  font: system

game:
  managers:
    map:
      field-size-x: 2000
      field-size-y: 1000
      road-width: 25
      base:
        height: 150
        width: 300
        max_hp: 10